### ISSUE TITLE
[FBMN][IIN] CAMERA integration into Ion Identity Networking

### ISSUE THREAD

**Issue by robinschmid** [DorresteinLaboratory/XCMS3_FeatureBasedMN#10]
regarding PR #9 

Hey everybody,

we can move the discussion here.

Example:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=fb1461d90990425295

Example quant table and edges file:
https://uni-muenster.sciebo.de/s/42LzDqtRw5WwAmy

The massive dataset for mzML files:
https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=a13ac7b7be1042

**The additional edges file (.csv)**
![image](https://user-images.githubusercontent.com/10366914/66756771-00aa1980-ee9b-11e9-9ced-a77dd61bb865.png)

- ID1, ID2: Row number of the (aligned) feature list
- EdgeType: To keep it easy on the GNPS side, it would be good if XCMS would use the same value: MS1 annotation
- Score: Any numerical value. We used the network size and some verifiers but it is kind of useless. (I did not include the correlation score, as it is calculated by a separate module/step in the process and people can use ion identity networking without it.)
- Annotation: Any String. 

**The feature table (quant file)**
![image](https://user-images.githubusercontent.com/10366914/66756735-f0923a00-ee9a-11e9-8b3d-3f76eaf3d733.png)
- The green columns were added for ion identity networking. They are not mandatory but add some useful metadata to each row. 
- Most important columns are:
  - annotation network number: This is the actual ion identity network number (IIN ID). All features here are in the same correlation group, are correlated to each other, and were identified as specific ions that all point to the same neutral molecule. 
  - best ion: Best ion identity choice (sometimes there are multiple possibilities – the best Ion Identity Network wins)
- Correlation group ID: We use the correlation to group aligned feature list rows – in our workflow, this does not mean that all features in a group are actually correlated. 
- Auto MS2 verify: Verification of multimers and in-source fragments
- Identified by n=: Ion Identity Network size
- Partners: List of all other IDs in this network
- Neutral M mass: Neutral mass of the molecule which is described by this network. (average over all m/z and ion identities).

**Comment by robinschmid** [comment]
Last email:
Rows without an annotation will result in an empty annotation network number. (they will only have the Correlation group ID).

> Problem is that we can also have pretty tricky cases:
That’s true, the results will never be perfect. I try to export the "best IIN identity" by using the largest ion identity network if there are multiple annotations for a feature. 
Your example would result in two annotation network numbers (IIN iDs) and as the network sizes are both 2 nodes you just randomly pick one and make it dominant.

Feature table would then be
Feature		annotation network number	Best ion
2875		1				[M+H-COCH2]+
2992		1				[M+H]+
3092		2				[M+H]+

... and all additional edges are exported (To avoid duplicates (e.g., 2875, 2992 and 2992,2875), you can control that every edge is only exported once if you only export it for the feature with the lower ID. 
2875, 2992
2992, 3092

  ID				adduct				pcgroup
2875               [M+H-COCH2]+ 944.68		116
2992 [M+H]+ 944.68 [M+H-C4H8]+ 1000.74	116
3092                    [M+H]+ 1000.74     		116


Cheers
Robin

**Comment by lfnothias** [comment]
This is great ! We are so close. Following up on the email.
I want to confirm that it is ok to have additional column information from CAMERA in the feature table of XCMS for FBMN. I will take care of checking that our dedicated XCMS table parser in the FBMN can handle it fine.

@jorainer I presume it is ok to start without the edge score, but it probably makes sense to find a way to have it in the future as this is key for the interpretation of the annotation and detect spurious ones.

**Comment by jorainer** [comment]
@lfnothias and @robinschmid, we've now implemented the functionality to extract the (adduct-based) feature annotations as described above and added the relevant example code to the Rmd file (it's also in PR #9).

For the example from above, the information from `CAMERA` for the respective *correlation group* is:

```r
> peaklist[peaklist$pcgroup == 116, c("adduct", "pcgroup")]
                                adduct pcgroup
2808                                       116
2870                                       116
2875               [M+H-COCH2]+ 944.68     116
2992 [M+H]+ 944.68 [M+H-C4H8]+ 1000.74     116
3092                    [M+H]+ 1000.74     116
```

We're extracting the following feature annotations for this:

```r
> res <- getFeatureAnnotations(xsaFA)
> res[res[, "correlation group ID"] == 116, ]
     row ID annotation network number     best ion identified by n= partners
2808   2808                        NA         <NA>               NA     <NA>
2870   2870                        NA         <NA>               NA     <NA>
2875   2875                       115 [M+H-COCH2]+                2     2992
2992   2992                       115       [M+H]+                2     2875
3092   3092                       116       [M+H]+                2     2992
     neutral M mass correlation group ID auto MS2 verify
2808             NA                  116              NA
2870             NA                  116              NA
2875       944.6803                  116              NA
2992       944.6803                  116              NA
3092      1000.7415                  116              NA
```

and the edge list for these:

```r
> edgelist[edgelist$pcgroup == 116, ]
      ID1  ID2       EdgeType Score                       Annotation Isotope
5054 2808 2870 MS1 annotation    NA                             <NA>    <NA>
5055 2808 2875 MS1 annotation    NA                             <NA>    <NA>
5056 2808 2992 MS1 annotation    NA                             <NA>    <NA>
5057 2808 3092 MS1 annotation    NA                             <NA>    <NA>
5058 2870 2875 MS1 annotation    NA                             <NA>    <NA>
5059 2870 2992 MS1 annotation    NA                             <NA>    <NA>
5060 2870 3092 MS1 annotation    NA                             <NA>    <NA>
5061 2875 2992 MS1 annotation    NA [M+H-COCH2]+ [M+H]+ dm/z=42.0023    <NA>
5062 2875 3092 MS1 annotation    NA                             <NA>    <NA>
5063 2992 3092 MS1 annotation    NA  [M+H-C4H8]+ [M+H]+ dm/z=56.0636    <NA>
     pcgroup
5054     116
5055     116
5056     116
5057     116
5058     116
5059     116
5060     116
5061     116
5062     116
5063     116
```

I hope it's OK like that. If not let me know and we'll fix.

**Comment by robinschmid** [comment]
This is fantastic. Thanks for the great work.

I dont know how flexible GNPS is at this point, so I have a few formatting remarks: (maybe @lfnothias  or @mwang87 can comment on the following)

- all MZmine output files are comma-separated

**Edge file:**
- better input 0 or -1 as the "Score" as this column is defined to be numeric (floating point)
- Can you remove the isotope column? All annotations are supposed to go into the Annotation column
- Can you add an option to either export all edges or only edges of annotated features?
- All edges without annotation should then be flagged with EdgeType=**MS1 correlation** to differentiate

**Quant table:**
- great output :)
- partners are separated by ; (semi-colon) if there are multiple
- In the MZmine version, all rows without ion identity are left with empty cells for IIN specific columns (this might be crucial for numeric columns - they should either be empty or 0 or -1. NA might crash)


MZmine feature table export:
![image](https://user-images.githubusercontent.com/10366914/66936487-13a91f00-f03e-11e9-97f7-889565486c0f.png)

**Comment by jorainer** [comment]
Thanks for the feedback @robinschmid !

Regarding the field separator, that's no problem at all, we can simply change parameter `sep` in the R function `write.table` which is used for the export in the workflow from `sep = "\t"` to `sep = ","`, just tell me what you need/want.

We will address the comments regarding the `Edge` file.

For the *Quant table*, I'll check, but I think we're already exporting `NA` as empty cells. If not we will change that.

**Comment by jorainer** [comment]
We've updated the workflow in the PR https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/pull/9 and also the functions in the github repo:

We dropped column `"Isotope"` and renamed column `"pcgroup"` to `"CorrelationGroup"`. Also, 
edges without adduct annotation have the `"EdgeType"` `"MS1 correlation"`, those with `"MS1 annotation"`.

```r
> edgelist[edgelist$CorrelationGroup == 1, ]
      ID1  ID2        EdgeType Score                           Annotation
4043 1483 1553 MS1 correlation    NA                                     
4044 1483 1908 MS1 correlation    NA                                     
4045 1483 1975 MS1 correlation    NA                                     
4046 1483 1997 MS1 correlation    NA                                     
4047 1483 2079 MS1 correlation    NA                                     
4048 1483 2597 MS1 correlation    NA                                     
4049 1553 1908 MS1 correlation    NA                                     
4050 1553 1975 MS1 correlation    NA                                     
4051 1553 1997 MS1 correlation    NA                                     
4052 1553 2079 MS1 correlation    NA                                     
4053 1553 2597 MS1 correlation    NA                                     
4054 1908 1975  MS1 annotation    NA       [M+K]+ [M+K+NH3]+ dm/z=17.0268
4055 1908 1997 MS1 correlation    NA                                     
4056 1908 2079  MS1 annotation    NA      [M+K]+ [M+K+HCOOH]+ dm/z=46.024
4057 1908 2597 MS1 correlation    NA                                     
4058 1975 1997 MS1 correlation    NA                                     
4059 1975 2079  MS1 annotation    NA [M+K+NH3]+ [M+K+HCOOH]+ dm/z=28.9971
4060 1975 2597 MS1 correlation    NA                                     
4061 1997 2079 MS1 correlation    NA                                     
4062 1997 2597 MS1 correlation    NA                                     
4063 2079 2597 MS1 correlation    NA                                     
     CorrelationGroup
4043                1
4044                1
4045                1
4046                1
4047                1
4048                1
4049                1
4050                1
4051                1
4052                1
4053                1
4054                1
4055                1
4056                1
4057                1
4058                1
4059                1
4060                1
4061                1
4062                1
4063                1

```

Regarding the quantification table: multiple partners are `;` separated.

```r
> quant_table[quant_table$`correlation group ID` == 1, ]
          mzmed    mzmin    mzmax    rtmed    rtmin    rtmax npeaks sample
FT1483 487.3526 487.3128 487.3625 302.5757 170.3271 377.9763     66     22
FT1553 509.4040 509.3318 509.4063 302.9501 214.5273 376.2055     50     22
FT1908 597.4577 597.3286 597.5100 301.2409 249.8720 410.6710     47     22
FT1975 614.4845 614.4466 614.5398 302.1363 252.8798 469.8716     29     21
FT1997 620.4429 620.3717 620.4950 301.2409 252.8798 374.4425     39     22
FT2079 643.4817 643.4415 643.5212 302.2689 231.1947 346.7806     41     19
FT2597 812.4132 812.2039 812.4155 302.9823 193.5003 355.9042     19     15
       row ID annotation network number     best ion identified by n=  partners
FT1483   1483                        NA         <NA>               NA      <NA>
FT1553   1553                        NA         <NA>               NA      <NA>
FT1908   1908                         1       [M+K]+                3 2079;1975
FT1975   1975                         1   [M+K+NH3]+                3 1908;2079
FT1997   1997                        NA         <NA>               NA      <NA>
FT2079   2079                         1 [M+K+HCOOH]+                3 1908;1975
FT2597   2597                        NA         <NA>               NA      <NA>
       neutral M mass correlation group ID auto MS2 verify
FT1483             NA                    1              NA
FT1553             NA                    1              NA
FT1908       558.4992                    1              NA
FT1975       558.4992                    1              NA
FT1997             NA                    1              NA
FT2079       558.4992                    1              NA
FT2597             NA                    1              NA
```

Note that we export with the option `na = ""` so all `NA` that you see above will be replaced with emtpy cells.

Regarding the option to only export edges and features with annotations, we have added an example to the workflow:

```r
quant_table_sub <- quant_table[!is.na(quant_table[, "best ion"]), ]
edgelist_sub <- edgelist[!is.na(edgelist$Annotation), ]
write.csv(edgelist_sub, file = "camera_iin_edgelist_sub.csv", row.names = FALSE,
          quote = FALSE, na = "")
write.table(quant_table_sub, file = "camera_iin_quant_table_sub.txt",
            row.names = FALSE, quote = FALSE, sep = "\t", na = "")
```

So, users are free to subset however they like in `R`.

**Comment by robinschmid** [comment]
> ```r
> CorrelationGroup
> 4043                1
> 4044                1
> ```
Oh Sorry, I did not recognize that pcgroup was in the edge file. This column also needs to be removed as this information is redundant - it is an attribute of the nodes in the quant table (correlation group id)
The generic "additional edges" format is:
ID1,ID2,Score,Annotation

I should definitely work more with R but my brain is stuck with object-oriented programming and mostly java. It is so much easier for me. Although, R and scripting in general offers so much for statistical analysis and plotting.

Cheers
Robin

**Comment by robinschmid** [comment]
@lfnothias can you test the workflow?

**Comment by jorainer** [comment]
Ah, java, good old days when I was also programming java :)

Regarding the `"CorrelationGroup"` column I have added in the edge file - I can remove that, no problem, I just thought it might be nice to have because it allows easier and faster subsetting in R. I was told that additional problems in that file would not be problematic, is that still true @lfnothias ? If not I'll remove it.

**Comment by lfnothias** [comment]
Excellent @jorainer @mar-garcia and @robinschmid. Yes, the "CorrelationGroup" should be only be in the quant table. Can you please provide me with the output files for the AGP test data, so I can test the workflow:
- New quant table (please keep same separator as before).
- New edge file.
- the MGF file (unless it is the same).

**Comment by robinschmid** [comment]
The quant table seems to be flexible for additional columns - I do not know how flexible the additional edges file is. However, we can just try it.

thanks @lfnothias

**Comment by jorainer** [comment]
Let's see how it goes. If there is a problem we can easily drop that column (or simply just not export it to csv).

**Comment by lfnothias** [comment]
Hi @jorainer 
Could you please share the output files so we can test the GNPS workflow ?

**Comment by jorainer** [comment]
Sure. The tables with **all** features:

[all.zip](https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/files/3765902/all.zip)

and with only those that have an adduct annotation:

[sub.zip](https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/files/3765903/sub.zip)

Let me know if something does not work so we can quickly fix.

**Comment by robinschmid** [comment]
Can you also provide the mgf files. Then I can give it a try.

**Comment by jorainer** [comment]
The zip file with the MS2 spectrum with the largest signal for each feature is below. 

[ms2spectra_maxTic.mgf.zip](https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/files/3766369/ms2spectra_maxTic.mgf.zip)

I didn't create one specifically for only those with adduct information, just let me know if you would also need that one.

**Comment by robinschmid** [comment]
I guess we have to wait for @lfnothias 

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=051be9c6b98342e9b94c3d17ae59691d
![image](https://user-images.githubusercontent.com/10366914/67486656-b5e38b00-f66c-11e9-9619-4d36904ca8d1.png)

**Comment by lfnothias** [comment]
Thanks @jorainer 
Yeah @robinschmid we need to update our XCMS parser. I am continuing this issue on GNPS GitHub.
https://github.com/CCMS-UCSD/GNPS_Workflows/issues/217

**Comment by lfnothias** [comment]
Everything is operational ! 
Last PR https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/pull/12
