### ISSUE TITLE
Extract MS2 data by "featureSpectra" or "spectra"

### ISSUE THREAD

**Issue by MuyaoXi9271** [DorresteinLaboratory/XCMS3_FeatureBasedMN#17]
Dear Experts,

Comparison "featureSpectra" with "spectra" on extraction of MS2 spectra.

The background is that I tried to extract MS2 spectra from XCMSnExp object (after doing gap-filling) by using "featureSpectra" featureSpectra(xcms_p_POS_g_r_g_fill, return.type = "MSpectra") and it succeeded. However, I noticed that a few MS2 spectra were indeed present in the XCMSnExp object, but they were not extracted by "featureSpectra". Instead, I found them from the results extracted by "spectra".

So my question is that is it possible to combine spectra obtained from "spectra", or what parameters could I add in "featureSpectra" to extract more ms2 spectra?

Bests,
Muyao

**Comment by lfnothias** [comment]
Dear Muyao,

The PR #16 by @jorainer seems to provide a work around this limitation. I am closing the issue but feel free to reopen if needed.
