### ISSUE TITLE
MsFeatures instead of CAMERA?

### ISSUE THREAD

**Issue by eterlova** [DorresteinLaboratory/XCMS3_FeatureBasedMN#18]
Hello all,

I want to run FBMN analysis on my LCMS data processed with `XCMS.` In your workflow (https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking-with-xcms3/) you recommend using `CAMERA` to identify adducts as a final step of preprocessing. However, CAMERA is not well-integrated with XCMS3 and to run it I am required to transform my `XCMSnExp` object into an older version and thus remove some qualities.

To go around this issue I am thinking to use `MsFeatures` to group my features and (maybe) `Spectra::matchMz` function for adduct annotation of MS1 spectra. What do you think about this plan? 

Best,
Lisa

**Comment by lfnothias** [comment]
Hi Lisa,
One way to use XCMS3 and CAMERA for FBMN x IIMN is shown here. It basically converts the CAMERA output into an edge list that we used for ion identity molecular networking. https://github.com/jorainer/xcms-gnps-tools/blob/master/customFunctions.R

I am not familiar with matchMz, but briefly looking at it, it seems that it annotates adducts by delta m/z, so it should help to reduce feature complexity, even if it is not as advanced as CAMERA (peak shape correlation analysis etc). If you are successful on this path, it would be really awesome to document it on the repository (like an example script).

**Comment by eterlova** [comment]
@lfnothias Thanks for the response! it is a good point that CAMERA has a sophisticated algorithm behind it, I think I will complement up my Spectra annotation with advanced grouping options from xcms, which also have the peak shape analysis, as well as abundance correlation, and RT grouping.

I am doing my current best to document my code, maybe I'll wright back when I am done for advice/review if that's okay.

Best,
Lisa

**Comment by eterlova** [comment]
While I have your attention, another question:

my R complains that it does not know formatSpectraForGNPS function which is used in the tutorial with only XCMS and CAMERA loaded. Do you happen to remember what package this function belongs?

Best,
Lisa
