### ISSUE TITLE
Update the XCMS3_Preprocessing.ipynb script

### ISSUE THREAD

**Issue by jorainer** [DorresteinLaboratory/XCMS3_FeatureBasedMN#2]
I guess we should also update the  XCMS3_Preprocessing.ipynb based on the XCMS3_Preprocessing.Rmd script - but I've no idea how... Could this be done by one of you guys @lfnothias @madeleineernst @rsilvabioinfo ?

**Comment by lfnothias** [comment]
@madeleineernst and @rsilvabioinfo 
Could you please look into updating the notebook based on changes made by @jorainer on the Rmd files ? This is not urgent, but it would be nice to have it done in the coming months.

**Comment by madeleineernst** [comment]
@jorainer I have now updated both XCMS3_Preprocessing.ipynb and XCMS3_Preprocessing_bacterial_samples.ipynb to reflect changes made in XCMS3_Preprocessing.Rmd and XCMS3_Preprocessing_bacterial_samples.Rmd. Note that both .ipynb files also contain a section 'Export MS2 consensus spectra' at the very end. Maybe worth updating the .Rmd scripts accordingly also?

**Comment by jorainer** [comment]
Thanks @madeleineernst ! I'll have a look at it and update accordingly.

**Comment by lfnothias** [comment]
Awesome ! 
When I compared the results between consensus spectra and maxTIC, the results of maxTIC were way better (in number of correct annotations), so I would suggest to indicate that the consensus spectra is an experimental feature, and that max_TIC is recommended by default.

**Comment by jorainer** [comment]
I've updated the Rmd files (also mentioning that this is an experimental feature) and made a PR (#7).

**Comment by madeleineernst** [comment]
Perfect! I merged the PR and also added that the consensus spectra option is an experimental feature to the .ipynb files.

**Comment by redbluewater** [comment]
This isn't an issue, but I am hijacking your thread to thank you all for your work on this. I have been looking for exactly this sort of integration, and was thrilled to find it here. I think this code will also provide guidance on getting MS2 data out of XCMS3. 
Thanks in advance for all your work on this. I look forward to using it with my own data.
